DROP SEQUENCE IF EXISTS seq_conference;
DROP SEQUENCE IF EXISTS seq_conference_talk;
DROP SEQUENCE IF EXISTS seq_country;
DROP SEQUENCE IF EXISTS seq_speaker;
DROP SEQUENCE IF EXISTS seq_speaker_talk;
DROP SEQUENCE IF EXISTS seq_talk;

DROP TABLE IF EXISTS conference CASCADE;
DROP TABLE IF EXISTS conference_talk CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS speaker CASCADE;
DROP TABLE IF EXISTS speaker_talk CASCADE;
DROP TABLE IF EXISTS talk CASCADE;
