DROP TABLE IF EXISTS conference CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS speaker CASCADE;
DROP TABLE IF EXISTS talk CASCADE;
DROP TABLE IF EXISTS conference_talk CASCADE;
DROP TABLE IF EXISTS speaker_talk CASCADE;
